### ISSUE TITLE
JSCAD not JsCad

### ISSUE THREAD

**Issue by z3dev** [simplyhexagonal/create-jscad-project#2]
Love this project! Very cool!

But the official name is JSCAD. 😄

**Comment by jeanlescure** [comment]
Alright, can't argue with that, specially when reported by an official JSCAD maintainer! Will fix soon 👍🏼

**Comment by z3dev** [comment]
😄 Love this project!

I'm going to use this cool tool to create some designs / training videos.

**Comment by jeanlescure** [comment]
Just released v1.1.6 with this change 🚀 

Cheers 🥂
